### ISSUE TITLE
Use yasmin discord API library

### ISSUE THREAD

**Issue by JABirchall** [botman/driver-discord#4]
So I noticed this no longer gets updated and doesn't work because of its dependency on PHPDiscord. However, maybe its time to revive this driver with [Yasmin](https://github.com/CharlotteDunois/Yasmin)? I used it to build my own bot and it works quite well and its built on top of react so the library supports concurrent connections.

**Comment by JABirchall** [comment]
I have a working discord driver here: https://github.com/JABirchall/botman-driver-discord using Yasmin.

**Comment by robjbrain** [comment]
Looks surprisingly simple! Can you put together some more docs/demo?

**Comment by JABirchall** [comment]
@robjbrain working on the readme now.

readme up: https://github.com/JABirchall/botman-driver-discord/blob/master/README.md
